name: Display File Contents

on:
  pull_request:
    types: [opened]

jobs:
  display_file_contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Read file contents
      id: read_file
      run: echo "::set-output name=content::$(cat your_file.txt)"

    - name: Update PR body with file contents
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const content = context.payload.pull_request.body + '\n\n```\n' + '${{ steps.read_file.outputs.content }}' + '\n```\n';
          await github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: content
          });
