name: Update PR Body with File Content

on:
  pull_request:
    types: [opened]

jobs:
  update-pr-body:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch File Content
      id: fetch_file_content
      run: |
        PR_BODY=$(jq -r '.pull_request.body' ${{ github.event_path }})
        FILE_URL=$(echo "$PR_BODY" | grep -oP 'https?://\S+new\.yaml')
        FILE_CONTENT=$(curl -sL $FILE_URL)
        echo "::set-output name=file_content::$FILE_CONTENT"

    - name: Update PR Body
      run: |
        FILE_CONTENT=${{ steps.fetch_file_content.outputs.file_content }}
        PR_BODY=$(jq -r '.pull_request.body' ${{ github.event_path }})
        UPDATED_PR_BODY="$PR_BODY\n\n$FILE_CONTENT"
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"$UPDATED_PR_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
