name: Update PR Body with File Content

on:
  pull_request:
    types: [opened]

jobs:
  update-pr-body:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch File Content
      id: fetch_file_content
      run: |
        FILE_CONTENT=$(curl -sL "https://raw.githubusercontent.com/${{ github.repository }}/main/new.yaml")
        echo "::set-output name=file_content::$FILE_CONTENT"

    - name: Update PR Body
      run: |
        FILE_CONTENT=${{ steps.fetch_file_content.outputs.file_content }}
        PR_BODY=$(jq -n --arg content "$FILE_CONTENT" '.pull_request.body |= . + "\n\n" + $content' $GITHUB_EVENT_PATH)
        echo "$PR_BODY" > $GITHUB_EVENT_PATH
