name: Display File Content on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  display-file-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract File URL from PR Body
      id: extract_url
      run: |
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        FILE_URL=$(echo "$PR_BODY" | sed -n 's/.\(https\?:\/\/[^ ]*new\.yaml\)./\1/p')
        echo "::set-output name=file_url::$FILE_URL"

    - name: Download and Display File Content
      id: download_and_display
      run: |
        FILE_URL=${{ steps.extract_url.outputs.file_url }}
        FILE_CONTENT=$(curl -sL $FILE_URL)
        echo "File content from PR body:"
        echo "$FILE_CONTENT"
